const HOK = [
    {Name: "Agudo", Picked: null, Banned: null},
    {Name: "Alessio", Picked: null, Banned: null},
    {Name: "Allain", Picked: null, Banned: null},
    {Name: "Angela", Picked: null, Banned: null},
    {Name: "Arke", Picked: null, Banned: null},
    {Name: "Arli", Picked: null, Banned: null},
    {Name: "Arthur", Picked: null, Banned: null},
    {Name: "Ata", Picked: null, Banned: null},
    {Name: "Athena", Picked: null, Banned: null},
    {Name: "Augran", Picked: null, Banned: null},
    {Name: "Biron", Picked: null, Banned: null},
    {Name: "Butterfly", Picked: null, Banned: null},
    {Name: "Cai Yan", Picked: null, Banned: null},
    {Name: "Charlotte", Picked: null, Banned: null},
    {Name: "Cirrus", Picked: null, Banned: null},
    {Name: "Consort Yu", Picked: null, Banned: null},
    {Name: "Da Qiao", Picked: null, Banned: null},
    {Name: "Daji", Picked: null, Banned: null},
    {Name: "Dharma", Picked: null, Banned: null},
    {Name: "Di Renjie", Picked: null, Banned: null},
    {Name: "Dian Wei", Picked: null, Banned: null},
    {Name: "Diaochan", Picked: null, Banned: null},
    {Name: "Dolia", Picked: null, Banned: null},
    {Name: "Donghuang", Picked: null, Banned: null},
    {Name: "Dr Bian", Picked: null, Banned: null},
    {Name: "Dun", Picked: null, Banned: null},
    {Name: "Dyadia", Picked: null, Banned: null},
    {Name: "Erin", Picked: null, Banned: null},
    {Name: "Fang", Picked: null, Banned: null},
    {Name: "Feyd", Picked: null, Banned: null},
    {Name: "Fuzi", Picked: null, Banned: null},
    {Name: "Gan & Mo", Picked: null, Banned: null},
    {Name: "Gao", Picked: null, Banned: null},
    {Name: "Garo", Picked: null, Banned: null},
    {Name: "Guan Yu", Picked: null, Banned: null},
    {Name: "Guiguzi", Picked: null, Banned: null},
    {Name: "Hanxin", Picked: null, Banned: null},
    {Name: "Heino", Picked: null, Banned: null},
    {Name: "Hou yi", Picked: null, Banned: null},
    {Name: "Huang Zhong", Picked: null, Banned: null},
    {Name: "Jing", Picked: null, Banned: null},
    {Name: "Kaizer", Picked: null, Banned: null},
    {Name: "Kongming", Picked: null, Banned: null},
    {Name: "Kui", Picked: null, Banned: null},
    {Name: "Lady Sun", Picked: null, Banned: null},
    {Name: "Lady Zen", Picked: null, Banned: null},
    {Name: "Lam", Picked: null, Banned: null},
    {Name: "Li Xin", Picked: null, Banned: null},
    {Name: "Lian Po", Picked: null, Banned: null},
    {Name: "Liang", Picked: null, Banned: null},
    {Name: "Liu Bang", Picked: null, Banned: null},
    {Name: "Liu Bei", Picked: null, Banned: null},
    {Name: "Liu Shan", Picked: null, Banned: null},
    {Name: "Loong", Picked: null, Banned: null},
    {Name: "Lubu", Picked: null, Banned: null},
    {Name: "Luara", Picked: null, Banned: null},
    {Name: "Luban No. 7", Picked: null, Banned: null},
    {Name: "Luna", Picked: null, Banned: null},
    {Name: "Mai Shiranui", Picked: null, Banned: null},
    {Name: "Marco Polo", Picked: null, Banned: null},
    {Name: "Mayene", Picked: null, Banned: null},
    {Name: "Meng Ya", Picked: null, Banned: null},
    {Name: "Menki", Picked: null, Banned: null},
    {Name: "Mi Yue", Picked: null, Banned: null},
    {Name: "Milady", Picked: null, Banned: null},
    {Name: "Ming", Picked: null, Banned: null},
    {Name: "Mozi", Picked: null, Banned: null},
    {Name: "Mulan", Picked: null, Banned: null},
    {Name: "Musashi", Picked: null, Banned: null},
    {Name: "Nakoruru", Picked: null, Banned: null},
    {Name: "Nezha", Picked: null, Banned: null},
    {Name: "Nuwa", Picked: null, Banned: null},
    {Name: "Pei", Picked: null, Banned: null},
    {Name: "Prince of Lanling", Picked: null, Banned: null},
    {Name: "Princess frost", Picked: null, Banned: null},
    {Name: "Sakeer", Picked: null, Banned: null},
    {Name: "Shangguang", Picked: null, Banned: null},
    {Name: "Shi", Picked: null, Banned: null},
    {Name: "Shouyue", Picked: null, Banned: null},
    {Name: "Sima Yi", Picked: null, Banned: null},
    {Name: "Sun Bin", Picked: null, Banned: null},
    {Name: "Sun Ce", Picked: null, Banned: null},
    {Name: "Ukyo Tachibana", Picked: null, Banned: null},
    {Name: "Wukong", Picked: null, Banned: null},
    {Name: "Wuyan", Picked: null, Banned: null},
    {Name: "Xiang Yu", Picked: null, Banned: null},
    {Name: "Xiao Qiao", Picked: null, Banned: null},
    {Name: "Xuance", Picked: null, Banned: null},
    {Name: "Yang Jian", Picked: null, Banned: null},
    {Name: "Yao", Picked: null, Banned: null},
    {Name: "Yaria", Picked: null, Banned: null},
    {Name: "Ying", Picked: null, Banned: null},
    {Name: "Yixing", Picked: null, Banned: null},
    {Name: "Yuhuan", Picked: null, Banned: null},
    {Name: "Zhang Fei", Picked: null, Banned: null},
    {Name: "Zhou Yu", Picked: null, Banned: null},
    {Name: "Zhuangzi", Picked: null, Banned: null},
    {Name: "Zilong", Picked: null, Banned: null},
    {Name: "Ziya", Picked: null, Banned: null},
]
